import type { FloorTable } from '@/types/database'

export const DEMO_TABLES: FloorTable[] = [
  {
    id: '1',
    profile_id: 'demo',
    name: 'Table 1',
    capacity: 4,
    shape: 'circle',
    position_x: 50,
    position_y: 50,
    width: 80,
    height: 80,
    status: 'occupied',
    current_session_id: '1',
    current_guest_name: 'Tomasz K.',
    session_start_time: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    zone: 'Main hall',
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    profile_id: 'demo',
    name: 'Table 2',
    capacity: 6,
    shape: 'rectangle',
    position_x: 200,
    position_y: 50,
    width: 120,
    height: 80,
    status: 'available',
    current_session_id: null,
    current_guest_name: null,
    session_start_time: null,
    zone: 'Main hall',
    notes: 'By the window',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    profile_id: 'demo',
    name: 'VIP',
    capacity: 8,
    shape: 'rectangle',
    position_x: 50,
    position_y: 180,
    width: 150,
    height: 100,
    status: 'reserved',
    current_session_id: null,
    current_guest_name: 'Reserved: Max W.',
    session_start_time: null,
    zone: 'VIP',
    notes: 'VIP zone',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    profile_id: 'demo',
    name: 'Table 3',
    capacity: 2,
    shape: 'circle',
    position_x: 280,
    position_y: 200,
    width: 60,
    height: 60,
    status: 'cleaning',
    current_session_id: null,
    current_guest_name: null,
    session_start_time: null,
    zone: 'Main hall',
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    profile_id: 'demo',
    name: 'Bar counter',
    capacity: 4,
    shape: 'rectangle',
    position_x: 380,
    position_y: 50,
    width: 40,
    height: 200,
    status: 'occupied',
    current_session_id: '2',
    current_guest_name: 'Lena S.',
    session_start_time: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    zone: 'Bar',
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
