import type { Guest } from '@/types/database'

export const DEMO_GUESTS: Guest[] = [
  {
    id: '1',
    profile_id: 'demo',
    name: 'Alex',
    phone: '+48 512 345 678',
    photo_url: null,
    notes: 'Regular guest, likes strong mixes',
    strength_preference: 'strong',
    flavor_profiles: ['fresh', 'citrus'],
    last_mix_snapshot: {
      id: 'snap_demo_1',
      tobaccos: [
        { tobacco_id: 'mh1', brand: 'Musthave', flavor: 'Pinkman', percent: 50, color: '#EC4899' },
        { tobacco_id: 'ds1', brand: 'Darkside', flavor: 'Supernova', percent: 25, color: '#06B6D4' },
        { tobacco_id: 'ds2', brand: 'Darkside', flavor: 'Bananapapa', percent: 25, color: '#FACC15' },
      ],
      total_grams: 20,
      strength: 'strong',
      compatibility_score: 85,
      bowl_type: 'Phunnel',
      heat_setup: { coals: 4, packing: 'dense' },
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    bonus_balance: 25.50,
    discount_percent: 10,
    total_spent: 540,
    loyalty_tier: 'gold',
    visit_count: 12,
    last_visit_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    profile_id: 'demo',
    name: 'Maria',
    phone: '+49 170 987 6543',
    photo_url: null,
    notes: 'Prefers light fruity mixes',
    strength_preference: 'light',
    flavor_profiles: ['fruity', 'sweet'],
    last_mix_snapshot: {
      id: 'snap_demo_2',
      tobaccos: [
        { tobacco_id: 'af4', brand: 'Al Fakher', flavor: 'Watermelon', percent: 60, color: '#FB7185' },
        { tobacco_id: 'fm3', brand: 'Fumari', flavor: 'Ambrosia', percent: 40, color: '#FBBF24' },
      ],
      total_grams: 18,
      strength: 'light',
      compatibility_score: 92,
      bowl_type: 'Turkish',
      heat_setup: { coals: 3, packing: 'fluffy' },
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    bonus_balance: 12,
    discount_percent: 5,
    total_spent: 280,
    loyalty_tier: 'silver',
    visit_count: 8,
    last_visit_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    profile_id: 'demo',
    name: 'David',
    phone: null,
    photo_url: null,
    notes: null,
    strength_preference: 'medium',
    flavor_profiles: ['spicy', 'citrus'],
    last_mix_snapshot: null,
    bonus_balance: 0,
    discount_percent: 0,
    total_spent: 45,
    loyalty_tier: 'bronze',
    visit_count: 3,
    last_visit_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    profile_id: 'demo',
    name: 'Anna',
    phone: '+48 601 555 123',
    photo_url: null,
    notes: 'VIP guest',
    strength_preference: 'medium',
    flavor_profiles: ['fruity', 'fresh'],
    last_mix_snapshot: {
      id: 'snap_demo_4',
      tobaccos: [
        { tobacco_id: 'ds3', brand: 'Darkside', flavor: 'Falling Star', percent: 45, color: '#F59E0B' },
        { tobacco_id: 'tg1', brand: 'Tangiers', flavor: 'Cane Mint', percent: 25, color: '#10B981' },
        { tobacco_id: 'mh5', brand: 'Musthave', flavor: 'Lemon', percent: 30, color: '#FCD34D' },
      ],
      total_grams: 22,
      strength: 'medium',
      compatibility_score: 78,
      bowl_type: 'Phunnel',
      heat_setup: { coals: 3, packing: 'semi-dense' },
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    bonus_balance: 45,
    discount_percent: 10,
    total_spent: 750,
    loyalty_tier: 'gold',
    visit_count: 15,
    last_visit_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    profile_id: 'demo',
    name: 'Tomasz',
    phone: null,
    photo_url: null,
    notes: 'First-time visitor, came with Anna',
    strength_preference: 'light',
    flavor_profiles: ['sweet', 'fruity'],
    last_mix_snapshot: null,
    bonus_balance: 0,
    discount_percent: 0,
    total_spent: 15,
    loyalty_tier: 'bronze',
    visit_count: 1,
    last_visit_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]
