import type { Reservation } from '@/types/database'

export const DEMO_RESERVATIONS: Reservation[] = [
  {
    id: '1',
    profile_id: 'demo',
    table_id: '3',
    guest_name: 'Tomasz Kowalski',
    guest_phone: '+48 512 345 678',
    guest_count: 4,
    reservation_date: new Date().toISOString().split('T')[0],
    reservation_time: '19:00',
    duration_minutes: 120,
    status: 'confirmed',
    notes: 'Birthday party',
    source: 'online',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    profile_id: 'demo',
    table_id: null,
    guest_name: 'Anna Nowak',
    guest_phone: '+48 601 987 654',
    guest_count: 2,
    reservation_date: new Date().toISOString().split('T')[0],
    reservation_time: '20:30',
    duration_minutes: 120,
    status: 'pending',
    notes: null,
    source: 'online',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    profile_id: 'demo',
    table_id: '1',
    guest_name: 'Max Weber',
    guest_phone: null,
    guest_count: 6,
    reservation_date: new Date().toISOString().split('T')[0],
    reservation_time: '21:00',
    duration_minutes: 180,
    status: 'confirmed',
    notes: 'VIP zone',
    source: 'phone',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    profile_id: 'demo',
    table_id: null,
    guest_name: 'Katarzyna Zielinska',
    guest_phone: '+48 505 123 456',
    guest_count: 3,
    reservation_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    reservation_time: '18:00',
    duration_minutes: 120,
    status: 'pending',
    notes: null,
    source: 'online',
    created_at: new Date().toISOString(),
  },
]
